version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    ports:
      - "5001:5001"
    networks:
      - monitoring-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:4000
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring-net

  frontend:
    build: ./frontend-ts
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"  # Maps container port 80 (nginx) to host port 3000
    networks:
      - monitoring-net


volumes:
  mongo-data:

networks:
  monitoring-net:
